### PR TITLE
delete 2 player

### PR DESCRIPTION
**Pull request by idealtrue0**
2 player 삭제

### CODE REVIEW

**Review by chear5967 — APPROVED** [review]
(:LGTM:) LG티비 꾸꾸루삥뽕

**Review by Choi-89 — APPROVED** [review]
૮꒰ྀི∩´ ꒳ `∩꒱ྀིა LGTM! ʕ ҂ •̻̀•́ ʔ

**Review by yuwol-9 — APPROVED** [review]
LGTM :):):):)

**Review by myfavoritekwon — APPROVED** [review]
( \_/)
( ' . ')
(> LGTM

**Pull request merged**
